# Generated by Django 3.2.9 on 2021-12-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studant',
            new_name='Student',
        ),
    ]
