# Generated by Django 4.0 on 2021-12-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_creation_alter_evaluation_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
